### ISSUE TITLE
Tiny simple editor

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro.IconPacks#12]
Add a tiny simple editor to change size, background and foreground and copy the result as Xaml into the clipboard...

**Comment by amkuchta** [comment]
@punker how do you plan on exposing the Xaml for the Icon so that the users can copy it for use?

**Comment by timunie** [comment]
Some thoughts on this
- If we use `HamburgerMenu` instead of `TabControl` we get more space
- We can use the new Space for providing a "customizing view" 
- There we may set `Width`, `Height`, `Brush (via ColorPicker)` etc
- Provide different Export options

Should I work this out this `Hacktober`? 

Preview: https://github.com/timunie/MahApps.Metro.IconPacks/tree/HamburgerMenuTest

Happy coding
Tim

**Comment by Insire** [comment]
there is a open [PR ](https://github.com/MahApps/MahApps.Metro.IconPacks/pull/51)that you can draw inspiration from for the color picker aswell. Regarding the xaml copy feature - you can serialize xaml objects to strings.
