### ISSUE TITLE
Designer and execution error due to "Flip" property

### ISSUE THREAD

**Issue by ghost** [MahApps/MahApps.Metro.IconPacks#30]
I'm getting the following error while trying to add an icon, they are working in 2 computers but not in the others.

` Flip property was already registered by 'MahApps_Metro_IconPacks_PackIcon`1_0_195866302' .`

**Comment by tgiachi** [comment]
Hi, i have same error!

![2017-01-17 12_18_55-cap3000 client - microsoft visual studio](https://cloud.githubusercontent.com/assets/942730/22018460/3f3bd0ae-dcaf-11e6-874d-e75d79a9d29c.png)

**Comment by punker76** [comment]
@tgiachi is your app public? or can you create a short sample which also produces this error? thx

**Comment by tgiachi** [comment]
Hi @punker76 , I can't post application because is company app. 
I have seen another error related icons: ControlEx  Kind Property was already registered

**Comment by punker76** [comment]
@tgiachi What's your Platform selection? Any CPU or x64? Do you added the Iconpacks via NuGet? Do you maybe use the MarkupExtensions?

**Comment by tgiachi** [comment]
Hi @punker76, I'm using Any CPU platform and i've added iconpacks using nuget. I'm using custom markup extensions, but the error is strange!

**Comment by darko1979** [comment]
I'm having the same problem but it appeared recently on my computer and only in wpf designer, applications builds fine without errors and displays icons without problems while running. On another computer (similar specs Window 10, Visual Studio 2015) designer works fine. I tried rolling back to versions 1.6 and 1.5 (because I did not have these errors a couple weeks ago) and it did not help. Here are screenshots of Visual Studio wpf designer from a computer with errors and from another without errors. It is the same project loaded on both computers.

![iconpack_error](https://cloud.githubusercontent.com/assets/23734311/22680621/47d2a728-ed09-11e6-9c79-70acf8a20b28.jpg)

![iconpack_noerror](https://cloud.githubusercontent.com/assets/23734311/22680634/56df11e8-ed09-11e6-8a31-386c8059d4da.jpg)

While I was typing this message I thought that this might be a problem due some Visual Studio caching so I deleted ".vs" folder in my solution folder and designer now works.
