### ISSUE TITLE
Flipped icon paths?

### ISSUE THREAD

**Issue by jotalanusse** [MahApps/MahApps.Metro.IconPacks#309]
**Describe the bug**
Icon paths for the `BoxIcons` icon library are all flipped vertically.

**To Reproduce**
1. Navigate to [PackIconBoxIconsDataFactory.cs](https://github.com/MahApps/MahApps.Metro.IconPacks/blob/a08c2d1af4817c56e7cf6b94b012229871ec50a7/src/MahApps.Metro.IconPacks/Icons/BoxIcons/PackIconBoxIconsDataFactory.cs).
3. Scroll down to any icon path definition.
4. It's flipped.

**Expected behavior**
Icon paths should not be flipped vertically

**Screenshots**
Flipped Discord logo as seen on a SVG path editor:
![Flipped Discord logo](https://user-images.githubusercontent.com/15149468/235182866-e24d9fc2-e0ac-438e-a74a-fe73fb51a5c3.png)

**Desktop Environment:**
 - IconPacks Version: v4.11.0

**Repo**
Does not apply.

**Additional context**
Does not apply.

**Comment by timunie** [comment]
I think this is known and comes due to the icon data. That's why some icon controls need to flip their content as well. See: https://github.com/MahApps/MahApps.Metro.IconPacks/blob/a08c2d1af4817c56e7cf6b94b012229871ec50a7/src/MahApps.Metro.IconPacks/Themes/WPF/PackIconBoxIcons.xaml#L33-L35

You may want to try https://github.com/MahApps/IconPacks.Browser which should get the path data correctly flipped if you export it to svg: 

![image](https://user-images.githubusercontent.com/47110241/235665533-eeedb94f-b392-4f28-bc19-d7d41d603b7d.png)

Result in Inkscape:
![image](https://user-images.githubusercontent.com/47110241/235665903-9cbd35ba-aa65-40b0-a98a-2385e31305ad.png)
