### ISSUE TITLE
Using FontAwesome icons inside Image leads to inversed visuals

### ISSUE THREAD

**Issue by gimmebytes** [MahApps/MahApps.Metro.IconPacks#59]
Hi there,

when using the current FontAwesome Iconpack (v1.9.1 or .0) the icons are displayed like this when embedding as Image inside XAML code using an custom converter (bool to icon):

![fontawesome](https://user-images.githubusercontent.com/1862500/31950389-c9556206-b8db-11e7-8a6f-abb47a071145.png)

Here is the code of the converter:

https://gist.github.com/gimmebytes/0d217c2261ce7ea60f33a2ae2db93958

And here the binding inside the XAML code:

`<Image Height="24" Width="24" Source="{Binding SomeObject.BoolField, Converter={StaticResource IconConverter}}" />`

When using the Modern Icon Pack everything is working fine. Havn't tested other packs yet.

Any help is appreciated, thanks in advance!

**Comment by punker76** [comment]
@gimmebytes Hi, this is caused by the raw original data from the FontAwesome icons. You must flip/scale the icons at y-axis by -1 like I does at the style

https://github.com/MahApps/MahApps.Metro.IconPacks/blob/6c829e868a3265903a3694641fb45fe57ca488c1/src/MahApps.Metro.IconPacks/Themes/PackIconFontAwesome.xaml#L43-L45

**Comment by gimmebytes** [comment]
@punker76 Thanks, that did the trick. I've updated the gist accordingly!
