### ISSUE TITLE
Icon for IconPacks library

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro.IconPacks#96]
It would be cool to have an awesome icon (logo) for this library itself. This icon (logo) will then be used then here on the GitHub repository and for the NuGet packages.

If you have an idea about an icon or if you have time and you are a designer then go for it 👍 😃 

Your name will be honored and linked to your site or whatever here on this repo and can be find at the README. It's also possible to pay out your work.

Thx!

**Comment by DeputyOfCopyPaster** [comment]
@punker76,
This designer's 'masterpiece' could be as a variant. 
![iconpack_01](https://user-images.githubusercontent.com/43616343/46850910-5bc7ad00-cdfe-11e8-9b81-0b372a7ff842.png)

**Comment by DeputyOfCopyPaster** [comment]
![iconpack_05](https://user-images.githubusercontent.com/43616343/46903523-de279e00-cede-11e8-9ca8-365bbbbd0383.png)
@punker76, Or like this one.

**Comment by timunie** [comment]
Hi all together /cc @punker76 

what do you think about this proposal? It is made with inkscape so anyone can modify it. As the file is svg it can also be converted to XAML. 
[IconPacksIcon_Suitcase.zip](https://github.com/MahApps/MahApps.Metro.IconPacks/files/3748119/IconPacksIcon_Suitcase.zip)

![IconPacksIcon_Suitcase](https://user-images.githubusercontent.com/47110241/67163547-a9131e80-f370-11e9-834b-61e42e573b1b.png)


Happy coding
Tim

**Comment by mgnslndh** [comment]
I like the simplicity of @timunie proposal. Here's another one based on an icon from the Noun project:

![test](https://user-images.githubusercontent.com/1139118/67163995-14abba80-f376-11e9-85ea-4cc06a20a8f3.png)

**Comment by timunie** [comment]
Hi @mgnslndh , your proposal is also very nice. I wanted to do a similar yesterday but I had not the time :-). 

Here is another one based on the Noun project build on a proposal of @punker76 on Twitter. 
![image](https://user-images.githubusercontent.com/47110241/67181003-94b83b80-f3db-11e9-9a42-98555ec4d0d1.png)

The MahApps Logo was transformed perspectivly but I don't know if it is 100% exact. 

I have to state that my current personal favorites are the two icons above this post. 

Happy choice @punker76 
Tim

**Comment by amkuchta** [comment]
Tossing my entry into the hat!

![IconPacks_LogoEntry](https://user-images.githubusercontent.com/6255186/67203812-0b543980-f3da-11e9-8442-135ba7697185.png)

**Comment by amkuchta** [comment]
Decided to also do one with a little less blue...

![IconPack_Alternate](https://user-images.githubusercontent.com/6255186/67295221-d9fc6c00-f4b4-11e9-8a85-40585333b528.png)

**Comment by timunie** [comment]
Ok one last idea from my side: A Stack of different icons with the MahApps Icon on Top :smile: 
![image](https://user-images.githubusercontent.com/47110241/67366839-86e9ee00-f574-11e9-92c5-ee2c273b23a6.png)

Happy chioce,
Tim

**Comment by amkuchta** [comment]
@timunie i like yours, but I would suggest reducing the number of layers (perhaps to 3?) with more spacing to make the icon more scalable.  It might also help to take a "duotone" approach with regards to the layers to help set the middle layer apart from the outer two (again, for scaling purposes)

**Comment by amkuchta** [comment]
I threw together a quick concept, but a few thoughts on it:
- Spacing between layers might be too much or too little
- For the middle and bottom layers, instead of duplicating the mustache, I could do a collection of evenly spaced icons (some Font Awesome, some Material, etc.) to give a better idea that it is an icon pack.  I just did the mustache to show the layering concept

![LayeredIcon](https://user-images.githubusercontent.com/6255186/67495899-9850fa00-f649-11e9-89fd-8a6ff000a1f9.png)


Thoughts?

**Comment by timunie** [comment]
Hi @amkuchta ,

thank you for your feedback. It is a first draft. As all the icons are *svg-files one can have several different styles of the same Icon. If my proposal win this competition I will have a look.

Happy drawing
Tim

**Comment by amkuchta** [comment]
Perhaps something along these lines, using the several different styles idea?  The first image shows a the image that could be used for larger icons (`256x256`, `512x512`):

![UpdateLayered](https://user-images.githubusercontent.com/6255186/67515690-2a1e2e80-f66d-11e9-976c-14da8125912e.png)

The second image shows a more scalable version for smaller use, without the icons on the lower layers; this could be used in places like the window icon for the Icon Browser:

![UpdateLayered_NoIcons](https://user-images.githubusercontent.com/6255186/67515726-3efac200-f66d-11e9-8209-95a4c3b84f32.png)

If anyone wants, I can work to clean it up (this was a really rough draft, so the image spacing and transforms don't quite match up as well as I would like).  Trying to take @timunie's idea and throw a twist on it (since his was so good it got me thinking a bit!)

**Comment by Templarian** [comment]
![icon-mustache](https://user-images.githubusercontent.com/338885/67521663-ee856380-f670-11e9-82a5-2fea6f3961f0.png) ![icon](https://user-images.githubusercontent.com/338885/67521608-d9103980-f670-11e9-8d56-8ded016dafc4.png) ![icon-open](https://user-images.githubusercontent.com/338885/67521617-dd3c5700-f670-11e9-85c7-2d239557a02b.png)

Minimal two tone. With the mustache, and the the other two without it. This could also be designed as a solid variant for an app icon.

**Comment by amkuchta** [comment]
@Templarian how well does that scale to smaller sizes? Specifically 16px, 32px, 64px since they are used for Windows app icons in the explorer

**Comment by Templarian** [comment]
@amkuchta Would have to make a solid variant that is a bit more "app icon". Could probably do that after work today before playing Outer Worlds tonight.

Should be possible to make this look nice at small size. 32x32. 16x16 would just use the mustache I would assume.

**Comment by Templarian** [comment]
@amkuchta Something like this might work. If this the direction Jan decides to go I'll design a full icon. These are more mocks to gauge interest.

![icon-mustache-solid](https://user-images.githubusercontent.com/338885/67532482-f8689000-f68b-11e9-9735-0a62583ad6ee.png)

**Comment by timunie** [comment]
If I were Jan @punker76  I would have no idea which one I should take. There are so many beautiful proposals :heart: 

Happy choice 
Tim

**Comment by amkuchta** [comment]
@Templarian I like the design overall - the only things that I think that I would change (though these are completely due to personal preference):

1) I'd lose the corner borders - in my mind, they remind me of my grandmother's cross-stitch patterns, and I can't shake that feeling lol.  Not to mention that I don't think that they would scale well to smaller sizes.
2) I'd round the corners of the square background - to me, this is more modern and more aesthetically pleasing, as the corners come across as less... aggressive?  That might not be the best term, but it's the closest I think that I am going to find.

Other than that, I love it.  I could also see this same design being used for the MA.M library, swapping out the fountain tip for a puzzle piece or an application window.  This would unify the two package icons, almost creating a "brand"

@punker76 obviously gets the final say, but I think that your design has my vote!

(Sorry this is so wordy - I finished building out my first custom mechanical keyboard today, and I am literally just finding reasons to type on it because I love it so much lol)

**Comment by Templarian** [comment]
Here is the zip:
[icon.zip](https://github.com/MahApps/MahApps.Metro.IconPacks/files/4095390/icon.zip)

**Comment by Templarian** [comment]
![stickermule](https://user-images.githubusercontent.com/338885/72870303-6f262100-3cad-11ea-858c-1400fe2517f2.png)
I've included templates for both Stickermule and Diginate Hexagon sticker templates.
[StickermuleDiginate.zip](https://github.com/MahApps/MahApps.Metro.IconPacks/files/4095560/StickermuleDiginate.zip)

**Comment by timunie** [comment]
@Templarian pretty nice sticker design. :+1:
